version: "3.9"

services:
    scr-codeigniter:
      platform: linux/amd64
      # build:
      #     context: .
      #     dockerfile: Dockerfile
      image: scr-codeigniter:1.0
      restart: unless-stopped
      ports:
        - "8080:8080"
        - "22:22"
      extra_hosts:
        - "host.docker.internal:host-gateway"
      networks:
        - scr-codeigniter-network
     # db mysql ${DB_DATABASE} //Busca do arquivo .env
    mysql:
      container_name: banco-mysql
      image: mysql:5.7.22
      restart: unless-stopped
      environment:
          MYSQL_DATABASE: ${DB_DATABASE}
          MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
          MYSQL_PASSWORD: ${DB_PASSWORD}
          MYSQL_USER: ${DB_USERNAME}
      volumes:
        - ./.docker/mysql/dbdata:/var/lib/mysql
      ports:
        - "3306:3306"
      networks:
        - scr-codeigniter-network

networks:
  scr-codeigniter-network:
    driver: bridge

#Doc. de utilizacao
# para acessar phpmyadmin no navegador: http://localhost:8899/ -  e a porta
# para acessar nginx(servidor) no navegador: http://localhost:8989/ - e a porta

#PHPMYADMIN info no file
# servidor: mysql
# user: root
# pass: root
